//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Musique.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class ArtistDbTable
    {
        public int Id { get; set; }
    
        public virtual UDbTable UDbTable { get; set; }
    }
}
